### ISSUE TITLE
Rollup - Gracefully handle scenarios where API is no longer available/accessible, or responds with failure messages.

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stigman-watcher#71]
This should include:
```[tasklist]
### Tasks
- [ ] https://github.com/NUWCDIVNPT/stigman-watcher/issues/62
- [ ] https://github.com/NUWCDIVNPT/stigman-watcher/issues/74
- [ ] https://github.com/NUWCDIVNPT/stigman-watcher/issues/75
- [ ] https://github.com/NUWCDIVNPT/stigman-watcher/issues/76
- [ ] https://github.com/NUWCDIVNPT/stigman-watcher/issues/77
- [ ] https://github.com/NUWCDIVNPT/stigman-watcher/issues/30
```
